### ISSUE TITLE
parse_retrosheet_pbp could not open file

### ISSUE THREAD

**Issue by thooper1** [beanumber/baseball_R#6] opened 2020-04-02 23:02 UTC
Please see the attached screenshot. 

I cannot get the parse_retrosheet_pbp function to create an "all" csv for downloaded data.  I have "retrosheet > unzipped > cwevent" in place.  However, the csv generated contains no data. 

Please advice on necessary steps to alleviate this. 
![Screenshot](https://user-images.githubusercontent.com/63005647/78306909-8d609680-7512-11ea-9b77-5de8f4febc09.PNG)

**Comment by beanumber** [comment] 2020-04-03 15:30
Duplicate of #2. Please see that thread @thooper1

**Closed by beanumber** 2020-04-03 15:30 UTC
